---
- hosts: all
  become: true
  tasks:
  - name: Install apache
    ansible.builtin.dnf:
      name: httpd
      state: present

  - name: ensure httpd started
    service:
      name: httpd
      state: started

  - name: Copy file with owner and permissions
    copy: 
      src: index.html
      dest: /var/www/html/index.html
      owner: root 
      group: root 
      mode: '0644'    

