---
- hosts: localhost
  connection: local

  tasks:
  - name: create a folder using loop
    file: 
      path: "/opt/{{item}}"
      state: directory
      mode: '0755'
    loop:
      - test1
      - test2
      - test3
